# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"u\n\x04Item\x12\x0f\n\x07item_id\x18\x01 \x01(\r\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04rate\x18\x03 \x01(\r\x12\x10\n\x08\x63\x61pacity\x18\x04 \x01(\x11\x12\r\n\x05start\x18\x05 \x01(\x07\x12\x0b\n\x03\x65nd\x18\x06 \x01(\x07\x12\x12\n\nupdated_at\x18\x07 \x01(\x07\"\xf2\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x16\n\x0ereferral_count\x18\x04 \x01(\r\x12\x16\n\x0ementions_count\x18\x05 \x01(\r\x12\x0f\n\x07\x62\x61lance\x18\x06 \x01(\x03\x12\r\n\x05spent\x18\x07 \x01(\x01\x12\x14\n\x05items\x18\x08 \x03(\x0b\x32\x05.Item\x12\r\n\x05tasks\x18\t \x03(\t\x12\x1a\n\x12user_referral_code\x18\n \x01(\t\x12\x13\n\x0blast_update\x18\x0b \x01(\x07\x12\x11\n\treactions\x18\x0c \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEM']._serialized_start=14
  _globals['_ITEM']._serialized_end=131
  _globals['_USER']._serialized_start=134
  _globals['_USER']._serialized_end=376
# @@protoc_insertion_point(module_scope)
